# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top200', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
